name: Cache the blog binary
description: A simple wrapper around actions/cache for this specific use-case
outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache@v4
      with:
        path: ./bin/blog
        key: blog-binary-${{ hashFiles('Dockerfile', 'go.sum', 'cmd/**.go', 'pkg/**.go') }}

