name: "Import Mastodon Links"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: "go run ./ci pipelines import-mastodon-links"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
