name: "Import Mastodon Links"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: "go run ./ci pipelines import-mastodon-links"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
