name: CI

on: [push]

jobs:
  build-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.1.3
      with:
        go-version: "1.17.4"
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg
        key: ${{ runner.os }}-go-${{ hashFiles('./go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build CLI
      run: "cd cmd/blog && GOOS=linux GOARCH=amd64 go build -mod=mod -o ../../blog && cd -"
    - uses: actions/upload-artifact@v1
      with:
        name: blogcli
        path: blog

  build-and-deploy:
    needs:
      - build-tools
    runs-on: ubuntu-latest
    env:
      FEEDBIN_USER: ${{ secrets.FEEDBIN_USER }}
      FEEDBIN_PASSWORD: ${{ secrets.FEEDBIN_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: 0.92.1
        extended: true
    - uses: actions/download-artifact@v1
      with:
        name: blogcli
    - run: chmod +x ./blogcli/blog
    - run: ./blogcli/blog build-archive
    - run: hugo
    - run: ./blogcli/blog build-graph
    - run: ./blogcli/blog blogroll --output data/blogroll.json
    - run: hugo
    - run: "./blogcli/blog books gen-opml"
    - run: "./blogcli/blog search build-mapping"
    - run: "./blogcli/blog changes --since-rev $(curl https://zerokspot.com/.gitrev) --url > public/.changes.txt"

    # Prepare deployment
    - run: "sudo apt-get install -qq --yes git curl"
      if: github.ref == 'refs/heads/main'
    - run: "mkdir -p ~/.ssh && chmod 0700 ~/.ssh"
      if: github.ref == 'refs/heads/main'
    - run: "echo \"$SSH_PRIVATE_KEY\" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa"
      if: github.ref == 'refs/heads/main'
    - run: "echo ${{ github.sha }} > public/.gitrev"
      if: github.ref == 'refs/heads/main'

    - name: "Build site for preview.zerokspot.com"
      run: "hugo"
      if: github.ref == 'refs/heads/main'
    - run: "rsync -avz -e \"ssh -o StrictHostKeyChecking=no\" blogcli/blog www-zerokspot@zs-web-001.nodes.h10n.me:/srv/www/zerokspot.com/www/bin/"
      if: github.ref == 'refs/heads/main'
    - run: "cd public && rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz * .mapping.json.xz .gitrev www-zerokspot@zs-web-001.nodes.h10n.me:/srv/www/zerokspot.com/www/htdocs/"
      if: github.ref == 'refs/heads/main'
    - run: "ssh www-zerokspot@zs-web-001.nodes.h10n.me \"touch /srv/www/zerokspot.com/www/deployed\""
      if: github.ref == 'refs/heads/main'

    - uses: actions/upload-artifact@v1
      with:
        name: changes
        path: ./public/.changes.txt
      if: github.ref == 'refs/heads/main'

  mention:
    if: github.ref == 'refs/heads/main'
    needs:
      - build-and-deploy
    runs-on: ubuntu-latest
    container:
      image: "zerok/webmentiond:latest"
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: changes
    - run: "((test $(stat -c '%s' ./changes/.changes.txt) -gt 10) && (cat ./changes/.changes.txt | xargs -n 1 /usr/local/bin/webmentiond send)) || echo 'Nothing changed.'"
    - uses: zerok/pushover-action@master
      with:
        token: ${{ secrets.PUSHOVER_TOKEN }}
        user: ${{ secrets.PUSHOVER_USER }}
        message: CI completed

