name: CI

on: [push]

jobs:
  build:
    env:
      FEEDBIN_USER: ${{ secrets.FEEDBIN_USER }}
      FEEDBIN_PASSWORD: ${{ secrets.FEEDBIN_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
      OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    - run: go run ci/main.go
      if: github.ref != 'refs/heads/main'
    - run: go run ci/main.go --publish
      if: github.ref == 'refs/heads/main'

