name: "Update blogroll"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - run: "go run ./ci pipelines update-blogroll"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          FEEDBIN_USER: "${{ secrets.FEEDBIN_USER }}"
          FEEDBIN_PASSWORD: "${{ secrets.FEEDBIN_PASSWORD }}"
