name: "Update blogroll"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - run: "go run ./ci pipelines update-blogroll"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          FEEDBIN_USER: "${{ secrets.FEEDBIN_USER }}"
          FEEDBIN_PASSWORD: "${{ secrets.FEEDBIN_PASSWORD }}"
